--<ScriptOptions statementTerminator=";"/>

CREATE TABLE SYSCHECKS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CHECKDEFINITION LONG VARCHAR NOT NULL,
		REFERENCEDCOLUMNS null NOT NULL
	);

CREATE TABLE SYSTABLEPERMS (
		TABLEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		SELECTPRIV CHAR(1) NOT NULL,
		DELETEPRIV CHAR(1) NOT NULL,
		INSERTPRIV CHAR(1) NOT NULL,
		UPDATEPRIV CHAR(1) NOT NULL,
		REFERENCESPRIV CHAR(1) NOT NULL,
		TRIGGERPRIV CHAR(1) NOT NULL
	);

CREATE TABLE SYSROLES (
		UUID CHAR(36) NOT NULL,
		ROLEID VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		WITHADMINOPTION CHAR(1) NOT NULL,
		ISDEF CHAR(1) NOT NULL
	);

CREATE TABLE SYSUSERS (
		USERNAME VARCHAR(128) NOT NULL,
		HASHINGSCHEME VARCHAR(32672) NOT NULL,
		PASSWORD VARCHAR(32672) NOT NULL,
		LASTMODIFIED TIMESTAMP NOT NULL
	);

CREATE TABLE SYSTRIGGERS (
		TRIGGERID CHAR(36) NOT NULL,
		TRIGGERNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		EVENT CHAR(1) NOT NULL,
		FIRINGTIME CHAR(1) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		STATE CHAR(1) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		WHENSTMTID CHAR(36),
		ACTIONSTMTID CHAR(36),
		REFERENCEDCOLUMNS null,
		TRIGGERDEFINITION LONG VARCHAR,
		REFERENCINGOLD null,
		REFERENCINGNEW null,
		OLDREFERENCINGNAME VARCHAR(128),
		NEWREFERENCINGNAME VARCHAR(128),
		WHENCLAUSETEXT LONG VARCHAR
	);

CREATE TABLE COMMENTS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		SUBMITDATE TIMESTAMP NOT NULL,
		DESCRIPTION VARCHAR(800) NOT NULL,
		BOOKNAME VARCHAR(100) NOT NULL,
		APPROVED INTEGER NOT NULL,
		PHOTO VARCHAR(400) NOT NULL
	);
	
INSERT INTO COMMENTS (USERNAME, SUBMITDATE, DESCRIPTION, BOOKNAME, APPROVED, PHOTO) VALUES (?,?,?,?,?,?);

DELETE FROM COMMENTS WHERE USERNAME=?;

DELETE FROM COMMENTS WHERE ID=?;

SELECT * FROM COMMENTS WHERE APPROVED=1;

SELECT * FROM COMMENTS WHERE APPROVED=0;

SELECT * FROM COMMENTS WHERE (BOOKNAME=? AND APPROVED=1);

SELECT * FROM COMMENTS WHERE (USERNAME=? AND APPROVED=1);

UPDATE COMMENTS SET APPROVED=1 WHERE ID=?;

CREATE TABLE BOOKS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		NAME VARCHAR(100) NOT NULL,
		AUTHOR VARCHAR(100) NOT NULL,
		URL VARCHAR(100) NOT NULL,
		PHOTO VARCHAR(100) NOT NULL,
		DESCRIPTION VARCHAR(700) NOT NULL,
		PRICE REAL NOT NULL
	);

INSERT INTO BOOKS (NAME, AUTHOR, URL, PHOTO, DESCRIPTION, PRICE) VALUES (?,?,?,?,?,?);

DELETE FROM BOOKS WHERE NAME=?;

SELECT * FROM BOOKS;

SELECT * FROM BOOKS WHERE NAME=?;

SELECT * FROM BOOKS WHERE AUTHOR=?;
			
CREATE TABLE MESSAGES (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		MESSAGE VARCHAR(500) NOT NULL,
		SUBJECT VARCHAR(20) NOT NULL,
		RECEIPTDATE TIMESTAMP NOT NULL,
		REPLY VARCHAR(500) NOT NULL,
		ADMINREAD INTEGER NOT NULL,
		ADMINREPLY INTEGER NOT NULL,
		USERREAD INTEGER NOT NULL
	);
	
INSERT INTO MESSAGES (USERNAME, MESSAGE, SUBJECT, RECEIPTDATE, REPLY, ADMINREAD, ADMINREPLY, USERREAD) VALUES (?,?,?,?,?,?,?,?);

DELETE FROM MESSAGES WHERE USERNAME=?;

DELETE FROM MESSAGES WHERE ID=?;

SELECT * FROM MESSAGES;

SELECT * FROM MESSAGES WHERE USERNAME=?;

SELECT * FROM MESSAGES WHERE RECEIPTDATE>=? AND RECEIPTDATE<=?;

SELECT * FROM MESSAGES WHERE ADMINREPLY=0;

SELECT * FROM MESSAGES WHERE ADMINREPLY=0;

SELECT * FROM MESSAGES WHERE ADMINREPLY=1;

SELECT * FROM MESSAGES WHERE (USERNAME=? AND USERREAD=0);

UPDATE MESSAGES SET ADMINREAD=1 WHERE ID=?;

UPDATE MESSAGES SET ADMINREPLY=1, REPLY=? WHERE ID=?;

UPDATE MESSAGES SET USERREAD=1 WHERE ID=?;

CREATE TABLE SYSFOREIGNKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL,
		KEYCONSTRAINTID CHAR(36) NOT NULL,
		DELETERULE CHAR(1) NOT NULL,
		UPDATERULE CHAR(1) NOT NULL
	);

CREATE TABLE PURCHASED (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		BOOKNAME VARCHAR(100) NOT NULL,
		POSITION INTEGER NOT NULL
	);
	
INSERT INTO PURCHASED (USERNAME, BOOKNAME, POSITION) VALUES (?,?,0);

DELETE FROM PURCHASED WHERE USERNAME=?;

DELETE FROM PURCHASED WHERE BOOKNAME=?;

SELECT * FROM PURCHASED;

SELECT * FROM PURCHASED WHERE BOOKNAME=?;

SELECT * FROM PURCHASED WHERE USERNAME=?;

SELECT * FROM PURCHASED WHERE USERNAME=? AND BOOKNAME=?;

UPDATE PURCHASED SET POSITION=? WHERE (BOOKNAME=? AND USERNAME=?);

CREATE TABLE SYSSTATEMENTS (
		STMTID CHAR(36) NOT NULL,
		STMTNAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		TEXT LONG VARCHAR NOT NULL,
		LASTCOMPILED TIMESTAMP,
		COMPILATIONSCHEMAID CHAR(36),
		USINGTEXT LONG VARCHAR
	);

CREATE TABLE SYSSTATISTICS (
		STATID CHAR(36) NOT NULL,
		REFERENCEID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CREATIONTIMESTAMP TIMESTAMP NOT NULL,
		TYPE CHAR(1) NOT NULL,
		VALID null NOT NULL,
		COLCOUNT INTEGER NOT NULL,
		STATISTICS null NOT NULL
	);

CREATE TABLE SYSCONSTRAINTS (
		CONSTRAINTID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONSTRAINTNAME VARCHAR(128) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		STATE CHAR(1) NOT NULL,
		REFERENCECOUNT INTEGER NOT NULL
	);

CREATE TABLE SYSKEYS (
		CONSTRAINTID CHAR(36) NOT NULL,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSCOLPERMS (
		COLPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		TYPE CHAR(1) NOT NULL,
		COLUMNS null NOT NULL
	);

CREATE TABLE SYSSCHEMAS (
		SCHEMAID CHAR(36) NOT NULL,
		SCHEMANAME VARCHAR(128) NOT NULL,
		AUTHORIZATIONID VARCHAR(128) NOT NULL
	);

CREATE TABLE USERS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		EMAIL VARCHAR(50) NOT NULL,
		CITY VARCHAR(50) NOT NULL,
		STREET VARCHAR(50) NOT NULL,
		HOUSENUM INTEGER NOT NULL,
		POSTALCODE VARCHAR(7) NOT NULL,
		COUNTRY VARCHAR(50) NOT NULL,
		PHONENUM VARCHAR(10) NOT NULL,
		PASSWORD VARCHAR(8) NOT NULL,
		NICKNAME VARCHAR(20) NOT NULL,
		DESCRIPTION VARCHAR(50) NOT NULL,
		PHOTO VARCHAR(700) NOT NULL
	);

INSERT INTO USERS (USERNAME, EMAIL,
		CITY, STREET, HOUSENUM, POSTALCODE, COUNTRY, PHONENUM, PASSWORD, NICKNAME,
		DESCRIPTION, PHOTO) VALUES (?,?,?,?,?,?,?,?,?,?,?,?);

DELETE FROM USERS WHERE USERNAME=?;

SELECT * FROM USERS;

SELECT * FROM USERS WHERE USERNAME=?;

SELECT * FROM USERS WHERE USERNAME=? AND PASSWORD=?;

CREATE TABLE SYSPERMS (
		UUID CHAR(36) NOT NULL,
		OBJECTTYPE VARCHAR(36) NOT NULL,
		OBJECTID CHAR(36) NOT NULL,
		PERMISSION CHAR(36) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		ISGRANTABLE CHAR(1) NOT NULL
	);

CREATE TABLE SYSTABLES (
		TABLEID CHAR(36) NOT NULL,
		TABLENAME VARCHAR(128) NOT NULL,
		TABLETYPE CHAR(1) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		LOCKGRANULARITY CHAR(1) NOT NULL
	);

CREATE TABLE SYSSEQUENCES (
		SEQUENCEID CHAR(36) NOT NULL,
		SEQUENCENAME VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		SEQUENCEDATATYPE null NOT NULL,
		CURRENTVALUE BIGINT,
		STARTVALUE BIGINT NOT NULL,
		MINIMUMVALUE BIGINT NOT NULL,
		MAXIMUMVALUE BIGINT NOT NULL,
		INCREMENT BIGINT NOT NULL,
		CYCLEOPTION CHAR(1) NOT NULL
	);

CREATE TABLE SYSALIASES (
		ALIASID CHAR(36) NOT NULL,
		ALIAS VARCHAR(128) NOT NULL,
		SCHEMAID CHAR(36),
		JAVACLASSNAME LONG VARCHAR NOT NULL,
		ALIASTYPE CHAR(1) NOT NULL,
		NAMESPACE CHAR(1) NOT NULL,
		SYSTEMALIAS null NOT NULL,
		ALIASINFO null,
		SPECIFICNAME VARCHAR(128) NOT NULL
	);

CREATE TABLE LIKES (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		NICKNAME VARCHAR(20) NOT NULL,
		BOOKNAME VARCHAR(100) NOT NULL
	);

INSERT INTO LIKES (USERNAME, NICKNAME, BOOKNAME) VALUES (?,?,?);

DELETE FROM LIKES WHERE USERNAME=?;

DELETE FROM LIKES WHERE USERNAME=? AND BOOKNAME=?;

SELECT * FROM LIKES;

SELECT * FROM LIKES WHERE BOOKNAME=?;

SELECT * FROM LIKES WHERE USERNAME=?;

SELECT * FROM LIKES WHERE USERNAME=? AND BOOKNAME=?;


CREATE TABLE SYSDUMMY1 (
		IBMREQD CHAR(1)
	);

CREATE TABLE SYSCOLUMNS (
		REFERENCEID CHAR(36) NOT NULL,
		COLUMNNAME VARCHAR(128) NOT NULL,
		COLUMNNUMBER INTEGER NOT NULL,
		COLUMNDATATYPE null NOT NULL,
		COLUMNDEFAULT null,
		COLUMNDEFAULTID CHAR(36),
		AUTOINCREMENTVALUE BIGINT,
		AUTOINCREMENTSTART BIGINT,
		AUTOINCREMENTINC BIGINT
	);

CREATE TABLE SYSCONGLOMERATES (
		SCHEMAID CHAR(36) NOT NULL,
		TABLEID CHAR(36) NOT NULL,
		CONGLOMERATENUMBER BIGINT NOT NULL,
		CONGLOMERATENAME VARCHAR(128),
		ISINDEX null NOT NULL,
		DESCRIPTOR null,
		ISCONSTRAINT null,
		CONGLOMERATEID CHAR(36) NOT NULL
	);

CREATE TABLE SYSDEPENDS (
		DEPENDENTID CHAR(36) NOT NULL,
		DEPENDENTFINDER null NOT NULL,
		PROVIDERID CHAR(36) NOT NULL,
		PROVIDERFINDER null NOT NULL
	);

CREATE TABLE TRANSACTIONS (
		ID INTEGER DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		USERNAME VARCHAR(10) NOT NULL,
		BOOKNAME VARCHAR(100) NOT NULL,
		PRICE REAL NOT NULL,
		SUBMITDATE TIMESTAMP NOT NULL
	);
	
INSERT INTO TRANSACTIONS (USERNAME, BOOKNAME, PRICE, SUBMITDATE) VALUES (?,?,?,?);

DELETE FROM TRANSACTIONS WHERE USERNAME=?;

DELETE FROM TRANSACTIONS WHERE BOOKNAME=?;

SELECT * FROM TRANSACTIONS;

SELECT * FROM TRANSACTIONS WHERE BOOKNAME=?;

SELECT * FROM TRANSACTIONS WHERE USERNAME=?;

SELECT * FROM TRANSACTIONS WHERE USERNAME=? AND BOOKNAME=?;

SELECT * FROM TRANSACTIONS WHERE SUBMITDATE>=? AND SUBMITDATE<=?;

CREATE TABLE SYSFILES (
		FILEID CHAR(36) NOT NULL,
		SCHEMAID CHAR(36) NOT NULL,
		FILENAME VARCHAR(128) NOT NULL,
		GENERATIONID BIGINT NOT NULL
	);

CREATE TABLE SYSVIEWS (
		TABLEID CHAR(36) NOT NULL,
		VIEWDEFINITION LONG VARCHAR NOT NULL,
		CHECKOPTION CHAR(1) NOT NULL,
		COMPILATIONSCHEMAID CHAR(36)
	);

CREATE TABLE SYSROUTINEPERMS (
		ROUTINEPERMSID CHAR(36) NOT NULL,
		GRANTEE VARCHAR(128) NOT NULL,
		GRANTOR VARCHAR(128) NOT NULL,
		ALIASID CHAR(36) NOT NULL,
		GRANTOPTION CHAR(1) NOT NULL
	);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX1 ON SYSROUTINEPERMS (GRANTEE ASC, ALIASID ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSTABLES_INDEX2 ON SYSTABLES (TABLEID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX1 ON SYSROLES (ROLEID ASC, GRANTEE ASC, GRANTOR ASC);

CREATE INDEX SYSROLES_INDEX2 ON SYSROLES (ROLEID ASC, ISDEF ASC);

CREATE UNIQUE INDEX SYSPERMS_INDEX1 ON SYSPERMS (UUID ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX2 ON SYSCONSTRAINTS (CONSTRAINTNAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSPERMS_INDEX3 ON SYSPERMS (GRANTEE ASC, OBJECTID ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX2 ON SYSCOLPERMS (COLPERMSID ASC);

CREATE INDEX SYSPERMS_INDEX2 ON SYSPERMS (OBJECTID ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX1 ON SYSFILES (FILENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX3 ON SYSALIASES (SCHEMAID ASC, SPECIFICNAME ASC);

CREATE UNIQUE INDEX SQL180226182508930 ON TRANSACTIONS (ID ASC);

CREATE UNIQUE INDEX SYSCONGLOMERATES_INDEX2 ON SYSCONGLOMERATES (CONGLOMERATENAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSUSERS_INDEX1 ON SYSUSERS (USERNAME ASC);

CREATE INDEX SYSTRIGGERS_INDEX3 ON SYSTRIGGERS (TABLEID ASC, CREATIONTIMESTAMP ASC);

CREATE INDEX SYSDEPENDS_INDEX1 ON SYSDEPENDS (DEPENDENTID ASC);

CREATE UNIQUE INDEX SYSCOLPERMS_INDEX1 ON SYSCOLPERMS (GRANTEE ASC, TABLEID ASC, TYPE ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SQL180226182508740 ON PURCHASED (ID ASC);

CREATE UNIQUE INDEX SYSKEYS_INDEX1 ON SYSKEYS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SQL180226182509050 ON MESSAGES (ID ASC);

CREATE UNIQUE INDEX SYSCONSTRAINTS_INDEX1 ON SYSCONSTRAINTS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSVIEWS_INDEX1 ON SYSVIEWS (TABLEID ASC);

CREATE INDEX SYSTABLEPERMS_INDEX3 ON SYSTABLEPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSFOREIGNKEYS_INDEX1 ON SYSFOREIGNKEYS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX1 ON SYSSCHEMAS (SCHEMANAME ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX1 ON SYSTRIGGERS (TRIGGERID ASC);

CREATE UNIQUE INDEX SQL180226182508120 ON COMMENTS (ID ASC);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX1 ON SYSSEQUENCES (SEQUENCEID ASC);

CREATE UNIQUE INDEX SQL180226182507670 ON USERS (ID ASC);

CREATE UNIQUE INDEX SQL180226182508420 ON LIKES (ID ASC);

CREATE INDEX SYSDEPENDS_INDEX2 ON SYSDEPENDS (PROVIDERID ASC);

CREATE INDEX SYSROUTINEPERMS_INDEX3 ON SYSROUTINEPERMS (ALIASID ASC);

CREATE UNIQUE INDEX SYSTABLES_INDEX1 ON SYSTABLES (TABLENAME ASC, SCHEMAID ASC);

CREATE INDEX SYSFOREIGNKEYS_INDEX2 ON SYSFOREIGNKEYS (KEYCONSTRAINTID ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX3 ON SYSCONGLOMERATES (TABLEID ASC);

CREATE UNIQUE INDEX SYSTRIGGERS_INDEX2 ON SYSTRIGGERS (TRIGGERNAME ASC, SCHEMAID ASC);

CREATE INDEX SYSCONGLOMERATES_INDEX1 ON SYSCONGLOMERATES (CONGLOMERATEID ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX2 ON SYSSTATEMENTS (STMTNAME ASC, SCHEMAID ASC);

CREATE UNIQUE INDEX SYSROLES_INDEX3 ON SYSROLES (UUID ASC);

CREATE INDEX SYSSTATISTICS_INDEX1 ON SYSSTATISTICS (TABLEID ASC, REFERENCEID ASC);

CREATE UNIQUE INDEX SYSCOLUMNS_INDEX1 ON SYSCOLUMNS (REFERENCEID ASC, COLUMNNAME ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX2 ON SYSTABLEPERMS (TABLEPERMSID ASC);

CREATE UNIQUE INDEX SYSSCHEMAS_INDEX2 ON SYSSCHEMAS (SCHEMAID ASC);

CREATE UNIQUE INDEX SYSFILES_INDEX2 ON SYSFILES (FILEID ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX2 ON SYSALIASES (ALIASID ASC);

CREATE INDEX SYSCOLUMNS_INDEX2 ON SYSCOLUMNS (COLUMNDEFAULTID ASC);

CREATE INDEX SYSCONSTRAINTS_INDEX3 ON SYSCONSTRAINTS (TABLEID ASC);

CREATE UNIQUE INDEX SQL180226182508580 ON BOOKS (ID ASC);

CREATE UNIQUE INDEX SYSTABLEPERMS_INDEX1 ON SYSTABLEPERMS (GRANTEE ASC, TABLEID ASC, GRANTOR ASC);

CREATE UNIQUE INDEX SYSALIASES_INDEX1 ON SYSALIASES (SCHEMAID ASC, ALIAS ASC, NAMESPACE ASC);

CREATE UNIQUE INDEX SYSCHECKS_INDEX1 ON SYSCHECKS (CONSTRAINTID ASC);

CREATE UNIQUE INDEX SYSROUTINEPERMS_INDEX2 ON SYSROUTINEPERMS (ROUTINEPERMSID ASC);

CREATE INDEX SYSCOLPERMS_INDEX3 ON SYSCOLPERMS (TABLEID ASC);

CREATE UNIQUE INDEX SYSSEQUENCES_INDEX2 ON SYSSEQUENCES (SCHEMAID ASC, SEQUENCENAME ASC);

CREATE UNIQUE INDEX SYSSTATEMENTS_INDEX1 ON SYSSTATEMENTS (STMTID ASC);

ALTER TABLE TRANSACTIONS ADD CONSTRAINT SQL180226182508930 PRIMARY KEY (ID);

ALTER TABLE COMMENTS ADD CONSTRAINT SQL180226182508120 PRIMARY KEY (ID);

ALTER TABLE LIKES ADD CONSTRAINT SQL180226182508420 PRIMARY KEY (ID);

ALTER TABLE BOOKS ADD CONSTRAINT SQL180226182508580 PRIMARY KEY (ID);

ALTER TABLE PURCHASED ADD CONSTRAINT SQL180226182508740 PRIMARY KEY (ID);

ALTER TABLE MESSAGES ADD CONSTRAINT SQL180226182509050 PRIMARY KEY (ID);

ALTER TABLE USERS ADD CONSTRAINT SQL180226182507670 PRIMARY KEY (ID);

